//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace ServiceSub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Musisz podaæ Login", AllowEmptyStrings = false)]
        public string userName { get; set; }

        [Required(ErrorMessage = "Musisz podaæ has³o", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        public string password { get; set; }

        public string FullName { get; set; }
    }
}
